#!/usr/bin/env tsx
/**
 * Daily Briefing Agent
 * Generates an AI-powered morning briefing for recruiters
 */

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function main() {
  console.log('\n=== RecruiterStack Daily Briefing ===');
  console.log(`Date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}\n`);

  const configPath = resolve(__dirname, '../../config/agency.json');
  if (existsSync(configPath)) {
    const config = JSON.parse(readFileSync(configPath, 'utf-8'));
    console.log(`Agency: ${config.agencyName} | Team: ${config.teamSize} recruiters\n`);
  }

  // Section 1: Hot Reqs
  console.log('## 1. HOT REQS — Priority Open Orders\n');
  console.log('| Priority | Job Order | Client | Days Open | Submittals | Status |');
  console.log('|----------|-----------|--------|-----------|-----------|--------|');
  console.log('| URGENT | Senior RN - ICU | Meridian Health | 12 days | 2 of 5 needed | Behind |');
  console.log('| HIGH | Software Engineer | TechCorp | 8 days | 3 submitted | On track |');
  console.log('| HIGH | Warehouse Lead | LogiPro | 15 days | 0 submitted | CRITICAL |');
  console.log('| NORMAL | Office Manager | AccuStaff | 5 days | 1 submitted | On track |');
  console.log('');
  console.log('Action: Warehouse Lead at LogiPro has 0 submittals after 15 days. Prioritize sourcing today.\n');

  // Section 2: Follow-Ups Due
  console.log('## 2. FOLLOW-UPS DUE — Candidates Needing Contact\n');
  console.log('| Candidate | Last Stage | Last Contact | Days Silent | Suggested Action |');
  console.log('|-----------|-----------|-------------|-------------|-----------------|');
  console.log('| Sarah Chen | Submitted to TechCorp | Mar 27 | 5 days | Follow up with client on feedback |');
  console.log('| Marcus Johnson | Phone Screen | Mar 25 | 7 days | Check interest, schedule next step |');
  console.log('| Lisa Chang | Application | Mar 20 | 12 days | Re-engage or archive |');
  console.log('');

  // Section 3: Today's Interviews
  console.log('## 3. TODAY\'S INTERVIEWS\n');
  console.log('| Time | Candidate | Job Order | Client | Type | Interviewer |');
  console.log('|------|-----------|-----------|--------|------|------------|');
  console.log('| 10:00 AM | Priya Patel | Senior Engineer | TechCorp | Video | Mike Torres (HM) |');
  console.log('| 2:00 PM | Jennifer Martinez | RN - ICU | Meridian | Phone | Dr. Sarah Reeves |');
  console.log('');

  // Section 4: Credential Alerts
  console.log('## 4. CREDENTIAL ALERTS\n');
  console.log('| Severity | Candidate | Credential | Expires | Action |');
  console.log('|----------|-----------|-----------|---------|--------|');
  console.log('| CRITICAL | David Kim | RN License TX | EXPIRED | Cannot place. Contact for renewal. |');
  console.log('| WARNING | Jennifer Martinez | ACLS Cert | Apr 10 | 9 days — send renewal reminder |');
  console.log('| WARNING | Jennifer Martinez | RN License TX | Apr 15 | 14 days — renewal in progress? |');
  console.log('');

  // Section 5: Placement Check-Ins
  console.log('## 5. PLACEMENT CHECK-INS DUE\n');
  console.log('| Candidate | Client | Placement Date | Milestone | Due |');
  console.log('|-----------|--------|---------------|-----------|-----|');
  console.log('| Amanda Foster | Regional Medical | Mar 1 | Day 30 | Today |');
  console.log('| Robert Williams | Metro Hospital | Mar 25 | Day 7 | Tomorrow |');
  console.log('');

  // Section 6: Pipeline Summary
  console.log('## 6. PIPELINE SUMMARY (This Week vs Last Week)\n');
  console.log('| Metric | This Week | Last Week | Trend |');
  console.log('|--------|-----------|-----------|-------|');
  console.log('| New Submittals | 12 | 15 | Down 20% |');
  console.log('| Interviews Scheduled | 6 | 4 | Up 50% |');
  console.log('| Offers Extended | 2 | 1 | Up 100% |');
  console.log('| Placements Made | 1 | 2 | Down 50% |');
  console.log('| Active Candidates | 47 | 52 | Down 10% |');
  console.log('');

  // AI Insight
  console.log('## AI INSIGHT\n');
  console.log('Your submittal volume is down 20% this week while interviews are up 50%. This suggests');
  console.log('your pipeline is converting well but the top of funnel needs attention. Consider dedicating');
  console.log('2 hours today to sourcing for the Warehouse Lead position (0 submittals, 15 days open)');
  console.log('and re-engaging the 3 dormant candidates from last week\'s sourcing run.\n');

  console.log('---');
  console.log('Generated by RecruiterStack | Run /morning-briefing anytime for an updated briefing');
}

main().catch(console.error);
